const CONSTANTS = {
  PORT: 3000,
  MIN_VALUE: 1,
  MAX_VALUE_CARDS: 56,
  MAX_VALUE_CARDS_PRO: 101,
  // MAX_VALUE_FOR_RANDOM: 34,
  WEBSOCKET_EVENTS: {
    NEW_USER: 'NEW_USER',
    ERR_USER: 'ERR_USER',
  },
};

export default CONSTANTS;