const CONSTANTS = {
  PORT: 3000,
  MAX_VALUE_CARDS: 58,
  MAX_VALUE_CARDS_PRO: 112,
  ARRAY_CARDS: {
    CARDS: [],
    CARDS_PRO: [],
  },
  WEBSOCKET_EVENTS: {
    NEW_USER: 'NEW_USER',
    UPDATE_USER: 'UPDATE_USER',
    ERR_USER: 'ERR_USER',
  },
  BASE_URL: 'localhost:3000',
};

export default CONSTANTS;