version: '2.4'

services:
  front-react:
    platform: linux/amd64
    build:
      context: ./client
      args:
        - NODE_ENV=development
    ports:
      - 5000:5000

  server-dev:
    platform: linux/amd64
    build:
      context: ./server
      args:
        - NODE_ENV=development
    ports:
      - 3000:3000

  postgres:
    platform: linux/amd64
    ports:
      - 5432:5432

  traefik:
    entrypoint: ["echo", "Disabled"]
