version: '2.4'

services:
  front-react:
    build:
      context: ./client
      args:
        - NODE_ENV="development"
    ports:
      - 5000:5000
  
  server-dev:
    build: 
      context: ./server
      args:
        - NODE_ENV="development"
    ports:
      - 3000:3000

  traefik:
    entrypoint: ["echo", "Disabled"]