version: '2.4'

services:
  front-react:
    restart: always
    container_name: frontend
    image: harry-fe-test
    environment:
      - API_HOSTNAME=backend
    volumes:
      - heroes:/client/public/images/heroes
    build:
      context: ./client
      args:
        NODE_ENV: development
    depends_on:
      - server-dev
    ports:
      - "5000:5000"

  server-dev:
    restart: always
    container_name: api
    image: harry-be-test
    environment:
      - DB_HOST=postgres
    build:
      context: ./server
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - heroes:/client/public/images/heroes
    depends_on:
      db:
        condition: service_healthy


  db: 
    image: postgres:13.2-alpine
    restart: always
    container_name: postgres
    volumes:
    - hp-db:/var/lib/postgres/data
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hp
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  hp-db:
  heroes: