version: '2.4'

services:
  front-react:
    build:
      context: ./client
      args:
        - NODE_ENV=development
    ports:
      - 5000:5000
  
  server-dev:
    container_name: ${API_HOST}
    build: 
      context: ./server
      args:
        - NODE_ENV=development
    ports:
      - 3000:3000

  postgres:
    ports:
      -5432:5432

  traefik:
    entrypoint: ["echo", "Disabled"]